# Generated by Django 6.0.3 on 2026-03-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_error',
            field=models.TextField(blank=True),
        ),
    ]
