# Generated by Django 6.0.3 on 2026-04-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_customer_ai_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ai_enabled',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
