# Generated by Django 6.0.3 on 2026-04-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_add_extra_fields_to_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
