# Generated by Django 6.0.3 on 2026-03-09 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='e.g. whatsapp, instagram', max_length=30, unique=True)),
                ('label', models.CharField(help_text='Display name e.g. WhatsApp', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Icon URL or CSS class', max_length=255)),
                ('color', models.CharField(blank=True, help_text='Brand color hex e.g. #25D366', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show this channel type in the UI')),
                ('supports_media', models.BooleanField(default=True)),
                ('supports_templates', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly label e.g. "Support WhatsApp"', max_length=100)),
                ('access_token', models.TextField(blank=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('phone_number_id', models.CharField(blank=True, max_length=100)),
                ('page_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='accounts.business')),
                ('channel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='integrations.channeltype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
