# Generated by Django 6.0.3 on 2026-03-11 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('integrations', '0002_seed_channel_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('facebook.com', 'Facebook Messenger'), ('whatsapp', 'WhatsApp Business')], max_length=20)),
                ('access_token', models.TextField(blank=True)),
                ('page_name', models.CharField(blank=True, max_length=255)),
                ('page_id', models.CharField(blank=True, max_length=100)),
                ('page_token', models.TextField(blank=True)),
                ('waba_id', models.CharField(blank=True, max_length=100)),
                ('waba_name', models.CharField(blank=True, max_length=255)),
                ('business_manager_id', models.CharField(blank=True, max_length=100)),
                ('business_manager_name', models.CharField(blank=True, max_length=255)),
                ('business_approved_status', models.CharField(blank=True, max_length=50)),
                ('business_verification_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to='accounts.business')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('business', 'source')},
            },
        ),
    ]
