# Generated by Django 6.0.3 on 2026-04-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_alter_sourceconnection_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceconnection',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
