import logging
import uuid
from django.utils import timezone
from rest_framework import status
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView

from integrations.models import Channel
from conversations.models import Customer, CustomerChannel, Message
from .auth import AppTokenAuthentication, IsAppClient
from .models import AppToken
from .serializers import (
    AppMessageCreateSerializer,
    AppMessageReadSerializer,
    AppMessageSerializer,
    CustomerPublicSerializer,
    SessionInitSerializer,
    SessionUpdateSerializer,
)
from .utility import handle_demo_prerequisite

logger = logging.getLogger(__name__)


def _broadcast_new_customer(customer):
    """Push a new_customer event to all agents' inbox sidebar."""
    from asgiref.sync import async_to_sync
    from channels.layers import get_channel_layer
    from conversations.serializers import CustomerSerializer

    channel_layer = get_channel_layer()
    if not channel_layer:
        return
    try:
        customer_data = CustomerSerializer(customer).data
        async_to_sync(channel_layer.group_send)(
            f'inbox_{customer.business_id}',
            {'type': 'inbox.new_customer', 'customer': customer_data},
        )
    except Exception:
        logger.exception('Failed to broadcast new_customer for customer %s', customer.id)


class ChannelInfoView(APIView):
    """
    GET /api/app/channel-info/?client_key=<uuid>

    Public. Returns basic channel/business info so the app can render a greeting
    or branding before a session is established.
    """
    authentication_classes = []
    permission_classes = [AllowAny]

    def get(self, request):
        client_key = request.query_params.get('client_key')
        if not client_key:
            return Response({'detail': 'client_key is required.'}, status=400)

        try:
            channel = Channel.objects.select_related('channel_type', 'business').get(
                client_key=client_key, channel_type__key='app', status='active'
            )
        except (Channel.DoesNotExist, ValueError):
            return Response({'detail': 'Channel not found or inactive.'}, status=404)

        return Response({
            'channel_id': str(channel.id),
            'channel_name': channel.name,
            'business_name': channel.business.name,
        })


class SessionInitView(APIView):
    """
    POST /api/app/session/init/

    Public. Creates or resumes an app session.
    On first call: creates Customer + CustomerChannel + AppToken.
    On return:     updates identity fields if provided; returns existing token.

    Body:
        client_key   — the channel's client key (from dashboard)
        anonymous_id — stable UUID generated by the client app and persisted locally
        name         — optional customer name
        email        — optional customer email
        phone        — optional customer phone

    Response:
        token      — bearer token; send as X-App-Token on all subsequent requests
        customer   — { id, name, email, phone }
    """
    authentication_classes = []
    permission_classes = [AllowAny]

    def post(self, request):
        serializer = SessionInitSerializer(data=request.data)
        if not serializer.is_valid():
            return Response(serializer.errors, status=400)

        data = serializer.validated_data
        is_demo = bool(data.get('demo_auth_key'))

        if is_demo:
            handle_demo_prerequisite(data)

        # Resolve the app channel
        try:
            channel = Channel.objects.select_related('channel_type', 'business').get(
                client_key=data['client_key'],
                channel_type__key='app',
                status='active',
            )
        except (Channel.DoesNotExist, ValueError):
            return Response({'detail': 'Invalid client key or channel not active.'}, status=404)

        anonymous_id = data['anonymous_id']

        # Find existing token (returning client)
        app_token = AppToken.objects.select_related('customer').filter(
            channel=channel, anonymous_id=anonymous_id
        ).first()

        if app_token:
            customer = app_token.customer
            # Update identity if new info was provided
            updated_fields = []
            if data['name'] and customer.name != data['name']:
                customer.name = data['name']
                updated_fields.append('name')
            if data['email'] and customer.email != data['email']:
                customer.email = data['email']
                updated_fields.append('email')
            if data['phone'] and customer.phone != data['phone']:
                customer.phone = data['phone']
                updated_fields.append('phone')
            if updated_fields:
                updated_fields.append('updated_at')
                customer.save(update_fields=updated_fields)

            if is_demo:
                Message.objects.filter(customer=customer, channel_type="app").order_by('-timestamp').delete()
        else:
            # New client — create Customer + CustomerChannel + AppToken
            customer = Customer.objects.create(
                business=channel.business,
                name=data['name'],
                email=data['email'],
                phone=data['phone'],
            )
            CustomerChannel.objects.create(
                customer=customer,
                channel_type='app',
                external_id=anonymous_id,
            )
            app_token = AppToken.objects.create(
                customer=customer,
                channel=channel,
                anonymous_id=anonymous_id,
            )
            _broadcast_new_customer(customer)

        return Response({
            'token': str(app_token.token),
            'customer': CustomerPublicSerializer(customer).data,
        }, status=status.HTTP_200_OK)


class SessionMeView(APIView):
    """
    GET  /api/app/session/me/  — get current customer profile
    PATCH /api/app/session/me/ — update name / email / phone
    Auth: X-App-Token
    """
    authentication_classes = [AppTokenAuthentication]
    permission_classes = [IsAppClient]

    def get(self, request):
        return Response(CustomerPublicSerializer(request.user.customer).data)

    def patch(self, request):
        serializer = SessionUpdateSerializer(data=request.data)
        if not serializer.is_valid():
            return Response(serializer.errors, status=400)

        customer = request.user.customer
        updated_fields = ['updated_at']
        for field in ('name', 'email', 'phone'):
            val = serializer.validated_data.get(field)
            if val is not None:
                setattr(customer, field, val)
                updated_fields.append(field)
        customer.save(update_fields=updated_fields)

        return Response(CustomerPublicSerializer(customer).data)


class AppMessagesView(APIView):
    """
    GET  /api/app/messages/
         ?limit=50&before=<message_id>  — cursor pagination (newest → oldest)
    POST /api/app/messages/
         { content: "..." }             — customer sends a message
    Auth: X-App-Token
    """
    authentication_classes = [AppTokenAuthentication]
    permission_classes = [IsAppClient]

    def get(self, request):
        app_token = request.user
        customer = app_token.customer

        qs = Message.objects.filter(customer=customer, channel_type="app").order_by('-timestamp')

        before_id = request.query_params.get('before')
        if before_id:
            try:
                pivot = Message.objects.get(id=before_id, customer=customer, channel="app")
                qs = qs.filter(timestamp__lt=pivot.timestamp)
            except Message.DoesNotExist:
                pass

        limit = min(int(request.query_params.get('limit', 50)), 100)
        total = qs.count()
        messages = list(reversed(list(qs[:limit])))

        return Response({
            'messages': AppMessageSerializer(messages, many=True).data,
            'has_more': total > limit,
        })

    def post(self, request):
        app_token = request.user
        serializer = AppMessageCreateSerializer(data=request.data)
        if not serializer.is_valid():
            return Response(serializer.errors, status=400)

        content = serializer.validated_data['content']
        customer = app_token.customer
        channel = app_token.channel

        message = Message.objects.create(
            customer=customer,
            speaker=Message.Speaker.CUSTOMER,
            channel_type=channel.channel_type.key,
            content_type=Message.ContentType.TEXT,
            content=content,
        )

        customer.last_channel = channel
        customer.last_message_at = timezone.now()
        customer.save(update_fields=['last_channel', 'last_message_at', 'updated_at'])

        # Broadcast to agents via WebSocket
        from conversations.services import MessageProcessor
        MessageProcessor._broadcast(customer, message)

        # Trigger AI auto-reply in background
        from conversations.ai_service import AIReplyService
        AIReplyService.dispatch(customer)

        return Response(AppMessageSerializer(message).data, status=status.HTTP_201_CREATED)


class AppMessageReadView(APIView):
    """
    POST /api/app/messages/read/
    Marks inbound (agent) messages as read from the customer's perspective.
    Body: { up_to_message_id: "<uuid>" }  OR  { message_ids: ["<uuid>", ...] }
    Auth: X-App-Token
    """
    authentication_classes = [AppTokenAuthentication]
    permission_classes = [IsAppClient]

    def post(self, request):
        app_token = request.user
        serializer = AppMessageReadSerializer(data=request.data)
        if not serializer.is_valid():
            return Response(serializer.errors, status=400)

        customer = app_token.customer
        data = serializer.validated_data

        if data.get('up_to_message_id'):
            try:
                pivot = Message.objects.get(id=data['up_to_message_id'], customer=customer)
                Message.objects.filter(
                    customer=customer,
                    timestamp__lte=pivot.timestamp,
                    is_read=False,
                ).update(is_read=True)
            except Message.DoesNotExist:
                return Response({'detail': 'Message not found.'}, status=404)
        else:
            Message.objects.filter(
                id__in=data['message_ids'],
                customer=customer,
            ).update(is_read=True)

        return Response({'detail': 'Marked as read.'})
